version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      security-patches:
        applies-to: security-updates
    commit-message:
      prefix: "deps"
