name: twilio-realtime-voice
metadata:
  template: twilio-realtime-voice@0.1.0
requiredVersions:
  azd: ">=1.14.0"
services:
  twilio-realtime-voice:
        project: server
        host: containerapp
        language: python
        docker:
          path: Dockerfile
          remoteBuild: true
pipeline:
  variables:
    - AZURE_LOCATION
    - AZURE_RESOURCE_GROUP
    - AZURE_CONTAINER_REGISTRY_ENDPOINT
    - SERVICE_API_ENDPOINTS
    - AZURE_VOICE_LIVE_ENDPOINT