name: voice-live-agent
metadata:
  template: voice-live-agent@0.1.0
requiredVersions:
  azd: ">=1.14.0"
services:
    app:
      project: ./server
      host: containerapp
      language: python
      docker:
        path: ./server/Dockerfile
        context: ./server
        remoteBuild: true
pipeline:
  variables:
    - AZURE_LOCATION
    - AZURE_RESOURCE_GROUP
    - AZURE_CONTAINER_REGISTRY_ENDPOINT
    - SERVICE_API_ENDPOINTS
    - AZURE_VOICE_LIVE_ENDPOINT