name: Azure Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/azure-dev.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Install Bicep CLI
      run: |
        curl -Lo bicep https://github.com/Azure/bicep/releases/download/v0.15.0/bicep-linux-x64
        chmod +x ./bicep
        sudo mv ./bicep /usr/local/bin/bicep

    - name: Deploy main.bicep at subscription scope
      run: |
        az deployment sub create \
          --location ${{ secrets.AZURE_REGION }} \
          --template-file infra/main.bicep \
          --parameters environmentName=${{ secrets.ENVIRONMENT_NAME }} \
                       location=${{ secrets.AZURE_REGION }} \
                       appExists=false

    - name: Output deployment results
      run: |
        echo "Deployment completed."
